In [1]:
import pandas as pd

In [12]:
column_names = ['index', 'heating_energy', 'cooling_energy', 'country', 'total_energy', 'region']
df = pd.read_csv('heating_and_cooling.csv', delimiter = ','
            , names = column_names)
df

      index  heating_energy  cooling_energy country  total_energy region
0         0        70181.07          571.60     USA      70752.67      D
1         1        79545.25          527.97     USA      80073.22      P
2         2         5796.05        20486.48     USA      26282.53      Y
3         3         8239.55        10069.80     ITA      18309.35      I
4         4        86888.04         7211.27     USA      94099.31      P
5         5        60645.48         5092.15     USA      65737.63      L
6         6         6318.99        23734.37     USA      30053.36      T
7         7        15491.76        12375.79     USA      27867.55      T
8         8        60137.17         4395.16     USA      64532.33      B
9         9         1612.05        23093.72     CHN      24705.77      C
10       10        49582.35         7640.32     USA      57222.67      R
11       11         2525.96         6924.59     USA       9450.55      Y
12       12        66002.88          645.41     USA      66648.29      H
13       13            0.00        36299.81     BRA      36299.81      B
14       14         9225.14         2460.77     BRA      11685.91      W
15       15            0.00        33858.79     BRA      33858.79      X
16       16        28590.30         4355.68     FRA      32945.98      H
17       17        37613.60        12466.46     USA      50080.06      Y
18       18          185.31        18157.75     ETH      18343.06      Z
19       19         2605.91        27145.31     USA      29751.22      L
20       20        25718.96         7464.06     ITA      33183.02      P
21       21         1864.28         6925.12     BRA       8789.40      I
22       22       159956.94          397.36     USA     160354.30      A
23       23        26836.07         6598.94     ITA      33435.01      S
24       24        11517.74        16041.68     USA      27559.42      C
25       25         1284.71        10056.67     BRA      11341.38      S
26       26            0.00        34527.02     BRA      34527.02      J
27       27        19367.93         5042.36     FRA      24410.29      M
28       28        11709.90         2015.79     NZL      13725.69      H
29       29       215812.13          729.14     CAN     216541.27      C
...     ...             ...             ...     ...           ...    ...
3003   3003         4445.42         8969.88     USA      13415.30      L
3004   3004        11756.36        17878.56     USA      29634.92      J
3005   3005        14227.40        17422.16     CHN      31649.56      T
3006   3006         7056.10        21953.75     USA      29009.85      S
3007   3007        29734.13         7974.10     BGR      37708.23      N
3008   3008        65130.87         4376.05     USA      69506.92      P
3009   3009        17095.43        13467.01     USA      30562.44      P
3010   3010        72107.83         6335.79     USA      78443.62      J
3011   3011            0.00        22611.11     BRA      22611.11      I
3012   3012        56043.27         2589.78     POL      58633.05      C
3013   3013        11442.35        19445.53     USA      30887.88      G
3014   3014          102.11        15905.37     BRA      16007.48      P
3015   3015        94186.89         5389.96     USA      99576.85      K
3016   3016         2187.23        12474.23     CHN      14661.46      D
3017   3017        57966.98         5357.96     USA      63324.94      T
3018   3018        51690.84         3487.61     POL      55178.45      G
3019   3019        41311.63         8922.38     USA      50234.01      P
3020   3020        25654.86        13602.65     CHN      39257.51      X
3021   3021        49461.82         5005.75     USA      54467.57      Z
3022   3022        25404.45         4874.42     ESP      30278.87      H
3023   3023        46766.33         9368.74     USA      56135.07      F
3024   3024           27.85        16563.62     BRA      16591.47      T
3025   3025         1889.72        28975.90     USA      30865.62      D
3026   3026        44426.02        10616.28     USA      55042.30      S
3027   3027         5186.94         4635.82     BRA       9822.76      T
3028   3028        25475.50        13439.91     CHN      38915.41      S
3029   3029         3516.48         8298.67     BRA      11815.15      U
3030   3030         8724.05         5883.68     USA      14607.73      B
3031   3031         1261.20        37794.47     IND      39055.67      G
3032   3032        78897.79         2033.22     RUS      80931.01      U

[3033 rows x 6 columns]

In [14]:
df = df.sort_values(['region'])
df

      index  heating_energy  cooling_energy country  total_energy region
2252   2252        13465.54        18573.33     CHN      32038.87      A
1510   1510        23007.55        17184.53     USA      40192.08      A
1022   1022        37789.99         8291.95     USA      46081.94      A
137     137         2869.61        15894.09     BRA      18763.70      A
2254   2254        46326.85         8915.70     USA      55242.55      A
755     755        25350.83         1473.03     USA      26823.86      A
1479   1479            0.46        21436.59     BRA      21437.05      A
2242   2242        67524.60         7771.53     USA      75296.13      A
2959   2959        20032.61        13837.23     USA      33869.84      A
1462   1462        56150.92         5427.10     USA      61578.02      A
763     763            5.90        26473.53     BRA      26479.43      A
2856   2856            0.00        44914.07     BRA      44914.07      A
1430   1430           14.40        19458.78     BRA      19473.18      A
2292   2292            0.00        39986.30     GUM      39986.30      A
1418   1418          229.20        31277.23     IND      31506.43      A
147     147        45840.67        21223.91     CHN      67064.58      A
289     289        64122.26         4277.96     USA      68400.22      A
1588   1588            0.00        34074.17     BRA      34074.17      A
2672   2672         7526.31        12585.39     ITA      20111.70      A
1729   1729        16526.90         1416.69     USA      17943.59      A
2694   2694        19233.98        17909.17     USA      37143.15      A
2147   2147        47580.52         4009.04     CHN      51589.56      A
2838   2838        86159.03         4117.21     CHN      90276.24      A
661     661        26395.48         4068.28     USA      30463.76      A
94       94        93691.91         4924.23     CHN      98616.14      A
1670   1670        34949.64         9859.47     USA      44809.11      A
2686   2686            0.00        22607.61     BRA      22607.61      A
1662   1662        59228.29         2726.26     POL      61954.55      A
2685   2685        24685.53         7595.46     JPN      32280.99      A
101     101        54590.80         3192.23     USA      57783.03      A
...     ...             ...             ...     ...           ...    ...
2495   2495        20408.43        12585.26     USA      32993.69      Z
2794   2794            0.00        33919.27     BRA      33919.27      Z
1860   1860          519.86        12699.62     BRA      13219.48      Z
2792   2792        93036.62         4193.08     USA      97229.70      Z
2057   2057        18036.50        11949.66     USA      29986.16      Z
1757   1757        11643.91        19133.88     USA      30777.79      Z
1036   1036         5254.34         5301.46     USA      10555.80      Z
1367   1367            0.00        40168.61     BRA      40168.61      Z
2054   2054        10924.30        18568.82     USA      29493.12      Z
1336   1336         6766.93         8963.79     ITA      15730.72      Z
2639   2639        55223.96         2620.42     POL      57844.38      Z
1541   1541         9832.42         3859.31     PER      13691.73      Z
2074   2074            1.61        29755.11     USA      29756.72      Z
987     987        39504.82        10164.76     CHN      49669.58      Z
1841   1841        46271.67         6254.98     USA      52526.65      Z
2610   2610       112541.21         2118.34     CAN     114659.55      Z
970     970         1520.93        29006.67     USA      30527.60      Z
786     786        61820.61         4333.12     USA      66153.73      Z
239     239        31756.77        11431.21     USA      43187.98      Z
781     781        86313.58          710.31     USA      87023.89      Z
2810   2810            0.00        37558.31     BRA      37558.31      Z
1844   1844          355.82        33315.92     USA      33671.74      Z
2515   2515        32491.97        11197.81     USA      43689.78      Z
1488   1488         7843.37         8154.91     PRT      15998.28      Z
1692   1692        74899.50         6646.24     USA      81545.74      Z
2318   2318        23860.15        11956.09     USA      35816.24      Z
986     986         1065.30        22074.82     BRA      23140.12      Z
211     211          373.18        42867.70     IND      43240.88      Z
224     224        11394.15        16697.02     USA      28091.17      Z
156     156        42364.80         7666.35     USA      50031.15      Z

[3033 rows x 6 columns]

In [22]:
df.groupby(['region'], as_index=False)['total_energy'].max()

   region  total_energy
0       A     160354.30
1       B     254308.05
2       C     216541.27
3       D     178143.34
4       E     167186.17
5       F     125968.11
6       G     169188.77
7       H     165984.91
8       I     168771.93
9       J     193405.70
10      K     201819.15
11      L     274345.72
12      M     150731.22
13      N     282275.74
14      O     170860.86
15      P     247590.13
16      Q     166772.25
17      R     193755.47
18      S     149645.36
19      T     242814.85
20      U     324698.73
21      V     195075.09
22      W     152885.65
23      X     186737.68
24      Y     184367.89
25      Z     151450.94

In [24]:
df.groupby(['region'])['total_energy'].max()

region
A    160354.30
B    254308.05
C    216541.27
D    178143.34
E    167186.17
F    125968.11
G    169188.77
H    165984.91
I    168771.93
J    193405.70
K    201819.15
L    274345.72
M    150731.22
N    282275.74
O    170860.86
P    247590.13
Q    166772.25
R    193755.47
S    149645.36
T    242814.85
U    324698.73
V    195075.09
W    152885.65
X    186737.68
Y    184367.89
Z    151450.94
Name: total_energy, dtype: float64

In [26]:
df.groupby(['region'], as_index=False)['total_energy'].max()

   region  total_energy
0       A     160354.30
1       B     254308.05
2       C     216541.27
3       D     178143.34
4       E     167186.17
5       F     125968.11
6       G     169188.77
7       H     165984.91
8       I     168771.93
9       J     193405.70
10      K     201819.15
11      L     274345.72
12      M     150731.22
13      N     282275.74
14      O     170860.86
15      P     247590.13
16      Q     166772.25
17      R     193755.47
18      S     149645.36
19      T     242814.85
20      U     324698.73
21      V     195075.09
22      W     152885.65
23      X     186737.68
24      Y     184367.89
25      Z     151450.94